-- AlterTable
ALTER TABLE "PricingSettings" ADD COLUMN     "screwLargePerSqm" DOUBLE PRECISION NOT NULL DEFAULT 2,
ADD COLUMN     "screwSmallPerBendM" DOUBLE PRECISION NOT NULL DEFAULT 3.3,
ADD COLUMN     "siliconeCoverageM" DOUBLE PRECISION NOT NULL DEFAULT 6;
